#!/bin/sh

# this file is sources
#
# returns the format, bitrate and samplerate of a file 
# returns error 1 when the file is does not exist

analyze_file() {

    if [ -f "$FILE" ]; then
	echo "Analyzing file: $FILE"
	FILEINFO=$(file -b "$FILE")
	FILETYPE=$(echo $FILEINFO | awk '{ print $1}')
	case "$FILETYPE" in
	    "FLAC")
		FILEBD=$(echo "$FILEINFO" | awk -F\, '{ print $2}'| sed 's/ //g')
		FILESR=$(echo "$FILEINFO" | awk -F\, '{ print $4}'| sed 's/ //g')
		;;
	    "RIFF")
		FILEBD=$(echo "$FILEINFO" | awk -F\, '{ print $4}'| sed 's/ //g')
		FILESR=$(echo "$FILEINFO" | awk -F\, '{ print $5}'| sed 's/^[ a-z]* //g')
		;;
	    *)
		die "Error: $FILE has an unknown filetype";;
	esac
	echo "  Filetype:   $FILETYPE"
	#echo "  Samplerate: $FILESR"
	#echo "  Bitdepth: $FILEBD"
	get_samplerate "$FILESR"
	get_bitdepth "$FILEBD"

    else
	die "Error: no such file $FILE"
    fi
    
}

