#!/bin/sh

# returns the variable SR containing one of the following:
# '44100', 88200' or '176400'
# '48000', '96000'  or '192000' 
# returns error 1 when other rate is chosen

get_samplerate(){

    VALIDRATES="44100', 88200', '176400', '48000', '96000'  or '192000'"
    # remove alphabetic characters and space 
    SR=$(echo $1 | sed 's/\([0-9.]*\)[ A-Za-z]*/\1/')

    # test if decimal separator is used (eg. 88.2Khz)
    if [[ $1 == *.* ]] ; then
	let SR=$( echo "$1*1000" | bc | sed 's/^\(.*\)\..*$/\1/' )
    fi
	
    case $SR in
	44100|88200|176400|48000|96000|192000) 
	    echo "Target samplerate: $SR Hz"
	    return 0 ;;
	*) 
	    echo "Error: Invalid samplerate ($SR) specified, use any of:"
	    echo "       $VALIDRATES"
	    return 1 ;;
    esac

}

## usage example:
#BLA="88.2 KHz"
#if get_samplerate $BLA; then
#    echo "samplerate: $SR"
#else
#    echo "error: samplerate ($SR) should be something else"
#fi

